server:
  port: 9898

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chetandas/microservices-config-repo.git
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.loadbalancer: DEBUG
