spring:
  datasource:
    url: jdbc:h2:~/Downloads/microservices-test/doctor-service/database/doctorsdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # or create-drop
    show-sql: true
  sql:
    init:
      mode: always
