spring:
  datasource:
    url: jdbc:h2:~/Downloads/mircoservices-test/patient-service/database/patientsdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # or create-drop
    show-sql: true
  sql:
    init:
      mode: always
